# Generated by Django 2.2.28 on 2023-06-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_hi'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='saddsads',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
